///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package View;
//
//import Controller.KH_GymDAO;
//import Model.KH_Gym;
//
//import java.sql.SQLException;
//import java.util.ArrayList;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//
///**
// *
// * @author Thanh Tuyá»�n
// */
//public class Thongtinhd extends javax.swing.JFrame {
//    KH_Gym k; 
//    ArrayList <KH_Gym> list;
//        /**
//     * Creates new form Thongtinhd
//     */
//    public Thongtinhd() {
//        initComponents();
//        k= new KH_Gym();
//        int i=1;
//        int sohd =i++;
//        txt_shd.setText(String.valueOf(sohd));
//                txt_tenKH.setText(k.getHoten());
//                txt_sdt.setText(k.getSdt());
//                txt_dc.setText(k.getDiachi());
//                txt_email.setText(k.getEmail());
//                txt_ngaydk.setText(k.getNgaydk());
//                txt_loaithe.setText(k.getLoaithe());
//                txt_gtien.setText(String.valueOf(k.getGiatien()));
//    }
//   
//    public void showTT(){
//        KH_GymDAO dao = new KH_GymDAO(); 
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jSeparator1 = new javax.swing.JSeparator();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel10 = new javax.swing.JLabel();
//        bt_thanhtoan = new javax.swing.JButton();
//        bt_thoat = new javax.swing.JButton();
//        txt_shd = new javax.swing.JTextField();
//        txt_tenKH = new javax.swing.JTextField();
//        txt_sdt = new javax.swing.JTextField();
//        txt_dc = new javax.swing.JTextField();
//        txt_email = new javax.swing.JTextField();
//        txt_ngaydk = new javax.swing.JTextField();
//        txt_loaithe = new javax.swing.JTextField();
//        txt_gtien = new javax.swing.JTextField();
//        jLabel11 = new javax.swing.JLabel();
//        txt_ngaytt = new javax.swing.JTextField();
//        rb1 = new javax.swing.JRadioButton();
//        rb2 = new javax.swing.JRadioButton();
//        jLabel12 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jLabel13 = new javax.swing.JLabel();
//        jLabel14 = new javax.swing.JLabel();
//        jLabel15 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jTextField2 = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel1.setText("THÃ”NG TIN HÃ“A Ä�Æ N");
//
//        jLabel2.setText("Sá»‘ hÃ³a Ä‘Æ¡n:");
//
//        jLabel3.setText("Há»� tÃªn  khÃ¡ch hÃ ng:");
//
//        jLabel4.setText("Sá»‘ Ä‘iá»‡n thoáº¡i:");
//
//        jLabel5.setText("Ä�á»‹a chá»‰:");
//
//        jLabel6.setText("Email:");
//
//        jLabel7.setText("NgÃ y Ä‘Äƒng kÃ½:");
//
//        jLabel9.setText("Loáº¡i tháº»:");
//
//        jLabel10.setText("GiÃ¡ tiá»�n");
//
//        bt_thanhtoan.setText("Thanh toÃ¡n");
//        bt_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                bt_thanhtoanActionPerformed(evt);
//            }
//        });
//
//        bt_thoat.setText("ThoÃ¡t");
//
//        txt_shd.setEditable(false);
//
//        txt_tenKH.setEditable(false);
//
//        txt_sdt.setEditable(false);
//
//        txt_dc.setEditable(false);
//
//        txt_email.setEditable(false);
//
//        txt_ngaydk.setEditable(false);
//
//        txt_loaithe.setEditable(false);
//
//        txt_gtien.setEditable(false);
//
//        jLabel11.setText("NgÃ y");
//
//        rb1.setText("Thanh toÃ¡n tháº» ngÃ¢n hÃ ng");
//
//        rb2.setText("Thanh toÃ¡n trá»±c tiáº¿p");
//        rb2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                rb2ActionPerformed(evt);
//            }
//        });
//
//        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel12.setText("Chá»�n hÃ¬nh thá»©c thanh toÃ¡n");
//
//        jButton1.setText("Tiáº¿p tá»¥c");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel13.setText("THÃ”NG TIN THáºº");
//
//        jLabel14.setText("Sá»‘ tháº»");
//
//        jLabel15.setText("Máº­t kháº©u");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(jSeparator1)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel8)
//                                .addGap(38, 38, 38)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                    .addComponent(jButton1)
//                                    .addGroup(layout.createSequentialGroup()
//                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                            .addComponent(jLabel14)
//                                            .addComponent(jLabel15))
//                                        .addGap(21, 21, 21)
//                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                            .addComponent(jTextField1)
//                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGap(52, 52, 52)))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(jLabel3)
//                                    .addComponent(jLabel2)
//                                    .addComponent(jLabel4)
//                                    .addComponent(jLabel5)
//                                    .addComponent(jLabel6)
//                                    .addComponent(jLabel7)
//                                    .addComponent(jLabel9)
//                                    .addComponent(jLabel10)
//                                    .addComponent(jLabel11)))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(0, 350, Short.MAX_VALUE)
//                                .addComponent(bt_thoat)
//                                .addGap(61, 61, 61)))
//                        .addGap(21, 21, 21)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addComponent(txt_shd)
//                            .addComponent(txt_tenKH)
//                            .addComponent(txt_sdt)
//                            .addComponent(txt_dc)
//                            .addComponent(txt_email)
//                            .addComponent(txt_ngaydk)
//                            .addComponent(txt_loaithe)
//                            .addComponent(txt_gtien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txt_ngaytt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(32, 32, 32))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(38, 38, 38)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(rb2)
//                            .addComponent(rb1))
//                        .addContainerGap(536, Short.MAX_VALUE))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addComponent(bt_thanhtoan)
//                        .addGap(52, 52, 52))))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(30, 30, 30)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(23, 23, 23)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(rb1)
//                        .addGap(18, 18, 18)
//                        .addComponent(rb2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel2)
//                            .addComponent(txt_shd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(18, 18, 18)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel3)
//                            .addComponent(txt_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(191, 191, 191)
//                        .addComponent(jLabel8)
//                        .addGap(28, 28, 28)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel11)
//                            .addComponent(txt_ngaytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(bt_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(bt_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addContainerGap())
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(18, 18, 18)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel4)
//                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(18, 18, 18)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel5)
//                                    .addComponent(txt_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel6)
//                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel7)
//                                    .addComponent(txt_ngaydk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(17, 17, 17)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(txt_loaithe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(jLabel9))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(txt_gtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(jLabel10)))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(6, 6, 6)
//                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel14)
//                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(33, 33, 33)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel15)
//                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
//                                .addComponent(jButton1))))))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void bt_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thanhtoanActionPerformed
//        // TODO add your handling code here:
//        k.setHoten(txt_tenKH.getText());
//            k.setSdt(txt_sdt.getText());
//            k.setDiachi(txt_dc.getText());
//            k.setEmail(txt_email.getText());
//            k.setLoaithe(txt_loaithe.getText());
//            k.setNgaydk(txt_ngaydk.getText());
//            k.setGiatien(Double.parseDouble(txt_gtien.getText()));
//            KH_GymDAO dao = new KH_GymDAO();
//        
//        try {
//            dao.getResultSet() ;
//        } catch (SQLException ex) {
//            Logger.getLogger(Thongtinhd.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }//GEN-LAST:event_bt_thanhtoanActionPerformed
//
//    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_rb2ActionPerformed
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
//        new Thongtinhd().setVisible(true);
//        this.dispose();
//    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Thongtinhd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Thongtinhd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Thongtinhd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Thongtinhd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Thongtinhd().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton bt_thanhtoan;
//    private javax.swing.JButton bt_thoat;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel13;
//    private javax.swing.JLabel jLabel14;
//    private javax.swing.JLabel jLabel15;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JSeparator jSeparator1;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JRadioButton rb1;
//    private javax.swing.JRadioButton rb2;
//    private javax.swing.JTextField txt_dc;
//    private javax.swing.JTextField txt_email;
//    private javax.swing.JTextField txt_gtien;
//    private javax.swing.JTextField txt_loaithe;
//    private javax.swing.JTextField txt_ngaydk;
//    private javax.swing.JTextField txt_ngaytt;
//    private javax.swing.JTextField txt_sdt;
//    private javax.swing.JTextField txt_shd;
//    private javax.swing.JTextField txt_tenKH;
//    // End of variables declaration//GEN-END:variables
//}
